name: Framework Release
on: 
  workflow_dispatch:
    inputs:
      new_version:
        description: "New sdk version"
        required: true
permissions:
  contents: read
jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      with: 
        ref: ${{ github.head_ref }}
    - name: update Podspec
      run: | 
        sed -i -e  's/spec.version = ".*"/spec.version = "${{ inputs.new_version }}"/' OpenTelemetry-Swift-BaggagePropagationProcessor.podspec
        sed -i -e  's/spec.version = ".*"/spec.version = "${{ inputs.new_version }}"/' OpenTelemetry-Swift-Instrumentation-NetworkStatus.podspec
        sed -i -e  's/spec.version = ".*"/spec.version = "${{ inputs.new_version }}"/' OpenTelemetry-Swift-Instrumentation-URLSession.podspec
        sed -i -e  's/spec.version = ".*"/spec.version = "${{ inputs.new_version }}"/' OpenTelemetry-Swift-Protocol-Exporter-Common.podspec
        sed -i -e  's/spec.version = ".*"/spec.version = "${{ inputs.new_version }}"/' OpenTelemetry-Swift-Protocol-Exporter-Http.podspec
        sed -i -e  's/spec.version = ".*"/spec.version = "${{ inputs.new_version }}"/' OpenTelemetry-Swift-SdkResourceExtension.podspec
        sed -i -e  's/spec.version = ".*"/spec.version = "${{ inputs.new_version }}"/' OpenTelemetry-Swift-PersistenceExporter.podspec

    - uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
      id: otelbot-token
      with:
        app-id: ${{ vars.OTELBOT_APP_ID }}
        private-key: ${{ secrets.OTELBOT_PRIVATE_KEY }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
      with:
        # not using secrets.GITHUB_TOKEN since pull requests from that token do not run workflows
        token: ${{ steps.otelbot-token.outputs.token }}
        branch-token: ${{ secrets.GITHUB_TOKEN }}
        branch: release/${{inputs.new_version}}
        commit-message: 'Release ${{inputs.new_version}}'
        title: 'Release ${{inputs.new_version}}'
        delete-branch: true
        body: >
          This PR is auto-generated by 
          [create-pull-request](https://github.com/peter-evans/create-pull-request).
        base: main
