name: Framework Release
on: 
  workflow_dispatch:
    inputs:
      new_version:
        description: "New sdk version"
        required: true
permissions:
  contents: read
jobs:
  Release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with: 
        ref: ${{ github.head_ref }}
    - name: update Podspec
      run: | 
        sed -i -e  's/spec.version = ".*"/spec.version = "${{ inputs.new_version }}"/' OpenTelemetry-Swift-BaggagePropagationProcessor.podspec
        sed -i -e  's/spec.version = ".*"/spec.version = "${{ inputs.new_version }}"/' OpenTelemetry-Swift-Instrumentation-NetworkStatus.podspec
        sed -i -e  's/spec.version = ".*"/spec.version = "${{ inputs.new_version }}"/' OpenTelemetry-Swift-Instrumentation-URLSession.podspec
        sed -i -e  's/spec.version = ".*"/spec.version = "${{ inputs.new_version }}"/' OpenTelemetry-Swift-Protocol-Exporter-Common.podspec
        sed -i -e  's/spec.version = ".*"/spec.version = "${{ inputs.new_version }}"/' OpenTelemetry-Swift-Protocol-Exporter-Http.podspec
        sed -i -e  's/spec.version = ".*"/spec.version = "${{ inputs.new_version }}"/' OpenTelemetry-Swift-SdkResourceExtension.podspec
        sed -i -e  's/spec.version = ".*"/spec.version = "${{ inputs.new_version }}"/' OpenTelemetry-Swift-PersistenceExporter.podspec

    - uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
      id: otelbot-token
      with:
        app-id: ${{ vars.OTELBOT_APP_ID }}
        private-key: ${{ secrets.OTELBOT_PRIVATE_KEY }}

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
      with:
        # not using secrets.GITHUB_TOKEN since pull requests from that token do not run workflows
        token: ${{ steps.otelbot-token.outputs.token }}
        branch-token: ${{ secrets.GITHUB_TOKEN }}
        branch: release/${{inputs.new_version}}
        commit-message: 'Release ${{inputs.new_version}}'
        title: 'Release ${{inputs.new_version}}'
        delete-branch: true
        body: >
          This PR is auto-generated by 
          [create-pull-request](https://github.com/peter-evans/create-pull-request).
        base: main
